onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /top/reset_pif/phy_ulpi_clk
add wave -noupdate /top/reset_pif/reset_n
add wave -noupdate /top/wb_pif/wb_clk
add wave -noupdate /top/wb_pif/wb_rst
add wave -noupdate /top/utmi_pif/utmi_clk
add wave -noupdate /top/utmi_pif/utmi_rst
add wave -noupdate /top/sram_pif/sram_clk
add wave -noupdate /top/sram_pif/sram_rst
add wave -noupdate -group DUT_TOP /top/dut/clk_i
add wave -noupdate -group DUT_TOP /top/dut/rst_i
add wave -noupdate -group DUT_TOP /top/dut/wb_addr_i
add wave -noupdate -group DUT_TOP /top/dut/wb_data_i
add wave -noupdate -group DUT_TOP /top/dut/wb_data_o
add wave -noupdate -group DUT_TOP /top/dut/wb_ack_o
add wave -noupdate -group DUT_TOP /top/dut/wb_we_i
add wave -noupdate -group DUT_TOP /top/dut/wb_stb_i
add wave -noupdate -group DUT_TOP /top/dut/wb_cyc_i
add wave -noupdate -group DUT_TOP /top/dut/inta_o
add wave -noupdate -group DUT_TOP /top/dut/intb_o
add wave -noupdate -group DUT_TOP /top/dut/dma_req_o
add wave -noupdate -group DUT_TOP /top/dut/dma_ack_i
add wave -noupdate -group DUT_TOP /top/dut/susp_o
add wave -noupdate -group DUT_TOP /top/dut/resume_req_i
add wave -noupdate -group DUT_TOP /top/dut/phy_clk_pad_i
add wave -noupdate -group DUT_TOP /top/dut/phy_rst_pad_o
add wave -noupdate -group DUT_TOP /top/dut/DataOut_pad_o
add wave -noupdate -group DUT_TOP /top/dut/TxValid_pad_o
add wave -noupdate -group DUT_TOP /top/dut/TxReady_pad_i
add wave -noupdate -group DUT_TOP /top/dut/DataIn_pad_i
add wave -noupdate -group DUT_TOP /top/dut/RxValid_pad_i
add wave -noupdate -group DUT_TOP /top/dut/RxActive_pad_i
add wave -noupdate -group DUT_TOP /top/dut/RxError_pad_i
add wave -noupdate -group DUT_TOP /top/dut/XcvSelect_pad_o
add wave -noupdate -group DUT_TOP /top/dut/TermSel_pad_o
add wave -noupdate -group DUT_TOP /top/dut/SuspendM_pad_o
add wave -noupdate -group DUT_TOP /top/dut/LineState_pad_i
add wave -noupdate -group DUT_TOP /top/dut/OpMode_pad_o
add wave -noupdate -group DUT_TOP /top/dut/usb_vbus_pad_i
add wave -noupdate -group DUT_TOP /top/dut/VControl_Load_pad_o
add wave -noupdate -group DUT_TOP /top/dut/VControl_pad_o
add wave -noupdate -group DUT_TOP /top/dut/VStatus_pad_i
add wave -noupdate -group DUT_TOP /top/dut/sram_adr_o
add wave -noupdate -group DUT_TOP /top/dut/sram_data_i
add wave -noupdate -group DUT_TOP /top/dut/sram_data_o
add wave -noupdate -group DUT_TOP /top/dut/sram_re_o
add wave -noupdate -group DUT_TOP /top/dut/sram_we_o
add wave -noupdate -group DUT_TOP /top/dut/rx_data
add wave -noupdate -group DUT_TOP /top/dut/rx_valid
add wave -noupdate -group DUT_TOP /top/dut/rx_active
add wave -noupdate -group DUT_TOP /top/dut/rx_err
add wave -noupdate -group DUT_TOP /top/dut/tx_data
add wave -noupdate -group DUT_TOP /top/dut/tx_valid
add wave -noupdate -group DUT_TOP /top/dut/tx_ready
add wave -noupdate -group DUT_TOP /top/dut/tx_first
add wave -noupdate -group DUT_TOP /top/dut/tx_valid_last
add wave -noupdate -group DUT_TOP /top/dut/mode_hs
add wave -noupdate -group DUT_TOP /top/dut/usb_reset
add wave -noupdate -group DUT_TOP /top/dut/usb_suspend
add wave -noupdate -group DUT_TOP /top/dut/usb_attached
add wave -noupdate -group DUT_TOP /top/dut/resume_req
add wave -noupdate -group DUT_TOP /top/dut/madr
add wave -noupdate -group DUT_TOP /top/dut/mdout
add wave -noupdate -group DUT_TOP /top/dut/mdin
add wave -noupdate -group DUT_TOP /top/dut/mwe
add wave -noupdate -group DUT_TOP /top/dut/mreq
add wave -noupdate -group DUT_TOP /top/dut/mack
add wave -noupdate -group DUT_TOP /top/dut/rst
add wave -noupdate -group DUT_TOP /top/dut/ma_adr
add wave -noupdate -group DUT_TOP /top/dut/ma2wb_d
add wave -noupdate -group DUT_TOP /top/dut/wb2ma_d
add wave -noupdate -group DUT_TOP /top/dut/ma_we
add wave -noupdate -group DUT_TOP /top/dut/ma_req
add wave -noupdate -group DUT_TOP /top/dut/ma_ack
add wave -noupdate -group DUT_TOP /top/dut/rf_re
add wave -noupdate -group DUT_TOP /top/dut/rf_we
add wave -noupdate -group DUT_TOP /top/dut/wb2rf_d
add wave -noupdate -group DUT_TOP /top/dut/rf2wb_d
add wave -noupdate -group DUT_TOP /top/dut/funct_adr
add wave -noupdate -group DUT_TOP /top/dut/idin
add wave -noupdate -group DUT_TOP /top/dut/ep_sel
add wave -noupdate -group DUT_TOP /top/dut/match
add wave -noupdate -group DUT_TOP /top/dut/dma_in_buf_sz1
add wave -noupdate -group DUT_TOP /top/dut/dma_out_buf_avail
add wave -noupdate -group DUT_TOP /top/dut/buf0_rl
add wave -noupdate -group DUT_TOP /top/dut/buf0_set
add wave -noupdate -group DUT_TOP /top/dut/buf1_set
add wave -noupdate -group DUT_TOP /top/dut/uc_bsel_set
add wave -noupdate -group DUT_TOP /top/dut/uc_dpd_set
add wave -noupdate -group DUT_TOP /top/dut/int_buf1_set
add wave -noupdate -group DUT_TOP /top/dut/int_buf0_set
add wave -noupdate -group DUT_TOP /top/dut/int_upid_set
add wave -noupdate -group DUT_TOP /top/dut/int_crc16_set
add wave -noupdate -group DUT_TOP /top/dut/int_to_set
add wave -noupdate -group DUT_TOP /top/dut/int_seqerr_set
add wave -noupdate -group DUT_TOP /top/dut/out_to_small
add wave -noupdate -group DUT_TOP /top/dut/csr
add wave -noupdate -group DUT_TOP /top/dut/buf0
add wave -noupdate -group DUT_TOP /top/dut/buf1
add wave -noupdate -group DUT_TOP /top/dut/frm_nat
add wave -noupdate -group DUT_TOP /top/dut/nse_err
add wave -noupdate -group DUT_TOP /top/dut/pid_cs_err
add wave -noupdate -group DUT_TOP /top/dut/crc5_err
add wave -noupdate -group DUT_TOP /top/dut/rf_resume_req
add wave -noupdate -group DUT_TOP /top/dut/LineState_r
add wave -noupdate -group DUT_TOP /top/dut/VStatus_r
add wave -noupdate -group DUT_TOP /top/dut/resume_req_r
add wave -noupdate -group DUT_TOP /top/dut/suspend_clr_wr
add wave -noupdate -group DUT_TOP /top/dut/suspend_clr
add wave -noupdate -group DUT_TOP /top/dut/ep_cnt
add wave -noupdate -group DUT_TOP /top/dut/ep_cnt2
add wave -noupdate -group DUT_TOP /top/dut/ep_check
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/phy_clk
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/rst
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/DataOut
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/TxValid
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/TxReady
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/DataIn
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/RxValid
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/RxActive
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/RxError
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/XcvSelect
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/TermSel
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/SuspendM
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/LineState
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/OpMode
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/usb_vbus
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/rx_data
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/rx_valid
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/rx_active
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/rx_err
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/tx_data
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/tx_valid
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/tx_valid_last
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/tx_ready
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/tx_first
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/mode_hs
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/usb_reset
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/usb_suspend
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/usb_attached
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/resume_req
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/suspend_clr
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/drive_k
add wave -noupdate -group DUT_UTMI_SIGNALS(U0) /top/dut/u0/drive_k_r
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/clk
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/rst
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/rx_data
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/rx_valid
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/rx_active
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/rx_err
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/tx_data
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/tx_valid
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/tx_valid_last
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/tx_ready
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/tx_first
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/tx_valid_out
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/mode_hs
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/usb_reset
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/usb_suspend
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/usb_attached
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/madr
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/mdout
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/mdin
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/mwe
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/mreq
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/mack
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/fa
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/idin
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/ep_sel
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/match
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/dma_in_buf_sz1
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/dma_out_buf_avail
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/nse_err
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/buf0_rl
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/buf0_set
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/buf1_set
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/uc_bsel_set
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/uc_dpd_set
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/int_buf1_set
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/int_buf0_set
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/int_upid_set
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/int_crc16_set
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/int_to_set
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/int_seqerr_set
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/out_to_small
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/csr
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/buf0
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/buf1
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_cs_err
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/crc5_err
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/frm_nat
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_OUT
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_IN
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_SOF
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_SETUP
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_DATA0
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_DATA1
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_DATA2
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_MDATA
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_ACK
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_NACK
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_STALL
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_NYET
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_PRE
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_ERR
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_SPLIT
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_PING
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/token_fadr
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/token_valid
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/frame_no
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/rx_data_st
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/rx_data_valid
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/rx_data_done
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/crc16_err
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/rx_seq_err
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/send_token
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/token_pid_sel
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/send_data
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/data_pid_sel
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/tx_data_st
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/rd_next
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/rx_dma_en
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/tx_dma_en
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/abort
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/idma_done
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/adr
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/size
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/sizu_c
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/buf_size
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/dma_en
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_bad
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_bad1
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/pid_bad2
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/hms_clk
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/hms_cnt
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/frame_no_r
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/frame_no_we
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/frame_no_same
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/mfm_cnt
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/sof_time
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/clr_sof_time
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/fsel
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/match_o
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/frame_no_we_r
add wave -noupdate -group Protocol_Layer(U1) /top/dut/u1/send_zero_length
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/phy_clk
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/wclk
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/rst
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/sram_adr
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/sram_din
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/sram_dout
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/sram_re
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/sram_we
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/madr
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/mdout
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/mdin
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/mwe
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/mreq
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/mack
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/wadr
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/wdout
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/wdin
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/wwe
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/wreq
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/wack
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/wsel
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/mcyc
add wave -noupdate -group DUT_Memory_Interface(U2) /top/dut/u2/wack_r
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/clk
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/wclk
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/rst
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/adr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/we
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/din
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/dout
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/inta
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/intb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/dma_req
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/dma_ack
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/idin
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep_sel
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/match
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/buf0_rl
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/buf0_set
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/buf1_set
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/uc_bsel_set
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/uc_dpd_set
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/int_buf1_set
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/int_buf0_set
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/int_upid_set
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/int_crc16_set
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/int_to_set
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/int_seqerr_set
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/out_to_small
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/buf0
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/buf1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/funct_adr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/dma_in_buf_sz1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/dma_out_buf_avail
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/frm_nat
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/utmi_vend_stat
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/utmi_vend_ctrl
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/utmi_vend_wr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/line_stat
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/usb_attached
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/mode_hs
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/suspend
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/attached
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/usb_reset
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/nse_err
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/pid_cs_err
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/crc5_err
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/rx_err
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/rf_resume_req
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep0_dout
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep1_dout
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep2_dout
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep3_dout
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep4_dout
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep5_dout
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep6_dout
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep7_dout
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep8_dout
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep9_dout
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep10_dout
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep11_dout
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep12_dout
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep13_dout
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep14_dout
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep15_dout
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep0_re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep1_re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep2_re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep3_re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep4_re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep5_re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep6_re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep7_re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep8_re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep9_re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep10_re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep11_re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep12_re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep13_re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep14_re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep15_re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep0_we
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep1_we
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep2_we
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep3_we
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep4_we
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep5_we
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep6_we
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep7_we
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep8_we
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep9_we
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep10_we
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep11_we
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep12_we
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep13_we
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep14_we
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep15_we
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep0_inta
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep1_inta
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep2_inta
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep3_inta
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep4_inta
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep5_inta
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep6_inta
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep7_inta
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep8_inta
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep9_inta
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep10_inta
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep11_inta
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep12_inta
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep13_inta
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep14_inta
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep15_inta
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep0_intb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep1_intb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep2_intb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep3_intb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep4_intb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep5_intb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep6_intb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep7_intb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep8_intb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep9_intb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep10_intb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep11_intb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep12_intb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep13_intb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep14_intb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep15_intb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep0_match
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep1_match
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep2_match
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep3_match
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep4_match
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep5_match
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep6_match
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep7_match
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep8_match
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep9_match
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep10_match
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep11_match
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep12_match
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep13_match
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep14_match
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep15_match
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep0_csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep1_csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep2_csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep3_csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep4_csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep5_csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep6_csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep7_csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep8_csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep9_csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep10_csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep11_csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep12_csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep13_csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep14_csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep15_csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep0_buf0
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep1_buf0
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep2_buf0
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep3_buf0
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep4_buf0
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep5_buf0
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep6_buf0
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep7_buf0
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep8_buf0
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep9_buf0
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep10_buf0
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep11_buf0
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep12_buf0
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep13_buf0
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep14_buf0
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep15_buf0
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep0_buf1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep1_buf1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep2_buf1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep3_buf1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep4_buf1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep5_buf1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep6_buf1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep7_buf1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep8_buf1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep9_buf1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep10_buf1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep11_buf1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep12_buf1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep13_buf1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep14_buf1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep15_buf1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep0_dma_in_buf_sz1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep1_dma_in_buf_sz1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep2_dma_in_buf_sz1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep3_dma_in_buf_sz1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep4_dma_in_buf_sz1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep5_dma_in_buf_sz1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep6_dma_in_buf_sz1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep7_dma_in_buf_sz1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep8_dma_in_buf_sz1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep9_dma_in_buf_sz1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep10_dma_in_buf_sz1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep11_dma_in_buf_sz1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep12_dma_in_buf_sz1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep13_dma_in_buf_sz1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep14_dma_in_buf_sz1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep15_dma_in_buf_sz1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep0_dma_out_buf_avail
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep1_dma_out_buf_avail
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep2_dma_out_buf_avail
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep3_dma_out_buf_avail
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep4_dma_out_buf_avail
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep5_dma_out_buf_avail
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep6_dma_out_buf_avail
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep7_dma_out_buf_avail
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep8_dma_out_buf_avail
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep9_dma_out_buf_avail
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep10_dma_out_buf_avail
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep11_dma_out_buf_avail
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep12_dma_out_buf_avail
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep13_dma_out_buf_avail
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep14_dma_out_buf_avail
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/ep15_dma_out_buf_avail
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/dtmp
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/main_csr
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/intb_msk
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/inta_msk
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/match_r1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/utmi_vend_stat_r
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/int_src_re
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/int_srcb
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/int_srca
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/attach_r
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/attach_r1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/attach
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/deattach
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/suspend_r
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/suspend_r1
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/suspend_start
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/suspend_end
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/usb_reset_r
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/rx_err_r
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/nse_err_r
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/pid_cs_err_r
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/crc5_err_r
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/rf_resume_req_r
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/inta_ep
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/intb_ep
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/inta_rf
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/intb_rf
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/utmi_vend_wr_r
add wave -noupdate -group CSR_Register_Interface(U4) /top/dut/u4/utmi_vend_ctrl_r
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/wb_clk
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/phy_clk
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/rst
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/wb_addr_i
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/wb_data_i
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/wb_data_o
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/wb_ack_o
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/wb_we_i
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/wb_stb_i
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/wb_cyc_i
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/ma_adr
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/ma_dout
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/ma_din
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/ma_we
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/ma_req
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/ma_ack
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/rf_re
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/rf_we
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/rf_din
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/rf_dout
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/state
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/next_state
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/wb_req_s1
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/wb_ack_d
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/wb_ack_s1
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/wb_ack_s1a
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/wb_ack_s2
add wave -noupdate -group DUT_WB_Interface(U5) /top/dut/u5/rf_we_d
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {15306 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 353
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {36750 ps}
